version: "3"

services:
    app:
        build: ./
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            PORT: "8080"
            VIRTUAL_PORT: 8080
            VIRTUAL_HOST: 2d.ssprojects.ca
            LETSENCRYPT_HOST: 2d.ssprojects.ca
            LETSENCRYPT_EMAIL: "fastf20@gmail.com"
        networks:
            - service-network
            - ship-network
        depends_on:
            - db
    db:
        image: postgres:11.2-alpine
        ports:
            - "5433:5432"
        environment:
            POSTGRES_PASSWORD: pgpw
            POSTGRES_DB: mydb
        volumes:
            - ~/dbShip:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - ship-network

networks:
    service-network:
        external: true
    ship-network:
        driver: bridge
