version: "3"

services:
    app:
        build: ./
        expose:
            - "8080"
        environment:
            PORT: 8080
            WEB_CONCURRENCY: 6
            VIRTUAL_PORT: 8080
            VIRTUAL_HOST: pack.ssprojects.ca
            LETSENCRYPT_HOST: pack.ssprojects.ca
            LETSENCRYPT_EMAIL: "fastf20@gmail.com"
        networks:
            - service-network
            - pack-network
        depends_on:
            - db
    db:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_DB: pack
            POSTGRES_USER: pack
            POSTGRES_PASSWORD: pgpw
        volumes:
            - ~/db_pack:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - pack-network

networks:
    service-network:
        external: true
    pack-network:
        driver: bridge
