version: "3"

services:
    app:
        build: ./
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
        networks:
            - service-network
            - pack-network
        volumes:
            - ./app:/app
        depends_on:
            - db
    db:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_PASSWORD: pgpw
            POSTGRES_DB: mydb
        volumes:
            - ~/dbShip:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - pack-network

networks:
    service-network:
        external: true
    pack-network:
        driver: bridge
