version: "3"

services:
    app:
        build: ./
        ports:
            - "8080:8080"
        expose:
            - "8080"
        environment:
            PORT: "8080"
            VIRTUAL_PORT: 8080
            VIRTUAL_HOST: 2d.ssprojects.ca
            LETSENCRYPT_HOST: 2d.ssprojects.ca
            LETSENCRYPT_EMAIL: "fastf20@gmail.com"
        networks:
            - service-network

networks:
    service-network:
        external: true
