version: "3"

services:
    app:
        build: ./
        ports:
            - "8080:8080"
        environment:
            PORT: 8080
            WEB_CONCURRENCY: 6
        networks:
            - service-network
            - ship-network
        #volumes:
        #    - ./app:/app
        depends_on:
            - db
    db:
        image: postgres:11.2-alpine
        environment:
            POSTGRES_DB: pack
            POSTGRES_USER: pack
            POSTGRES_PASSWORD: pgpw
        volumes:
            - ~/db_pack:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - ship-network

networks:
    service-network:
        external: true
    ship-network:
        driver: bridge
